"""Initial schema

Revision ID: 928559d964fb
Revises:
Create Date: 2026-09-05 23:44:43.376392

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "928559d964fb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "optimization_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cost_weight", sa.Float(), nullable=False),
        sa.Column("time_weight", sa.Float(), nullable=False),
        sa.Column("reliability_weight", sa.Float(), nullable=False),
        sa.Column("risk_weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column(
            "cargo_type",
            sa.Enum("GENERAL", "PERISHABLE", "HAZARDOUS", "FRAGILE", name="cargotype"),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("shipment_value", sa.Float(), nullable=False),
        sa.Column("delivery_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("STANDARD", "HIGH", "URGENT", name="shipmentpriority"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("route_name", sa.String(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("transit_time", sa.Float(), nullable=False),
        sa.Column("delay_probability", sa.Float(), nullable=False),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.Column("aggregate_risk", sa.Float(), nullable=False),
        sa.Column(
            "feasibility_status",
            sa.Enum("PENDING", "FEASIBLE", "INFEASIBLE", name="feasibilitystatus"),
            nullable=False,
        ),
        sa.Column("violated_constraints", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "optimization_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("recommended_route_id", sa.Uuid(), nullable=True),
        sa.Column("feasible_routes", sa.JSON(), nullable=False),
        sa.Column("infeasible_routes", sa.JSON(), nullable=False),
        sa.Column("route_scores", sa.JSON(), nullable=False),
        sa.Column("score_breakdown", sa.JSON(), nullable=False),
        sa.Column("constraint_results", sa.JSON(), nullable=False),
        sa.Column("tradeoffs", sa.JSON(), nullable=False),
        sa.Column("sensitivity", sa.JSON(), nullable=True),
        sa.Column("execution_time_ms", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["optimization_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommended_route_id"],
            ["routes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route_legs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column(
            "transport_mode",
            sa.Enum("SEA", "AIR", "RAIL", "ROAD", name="transportmode"),
            nullable=False,
        ),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risk_factors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("leg_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CONGESTION",
                "GEOPOLITICAL",
                "WEATHER",
                "OPERATIONAL",
                name="riskcategory",
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.Float(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["leg_id"],
            ["route_legs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_factors")
    op.drop_table("route_legs")
    op.drop_table("optimization_runs")
    op.drop_table("routes")
    op.drop_table("shipments")
    op.drop_table("optimization_profiles")
    # ### end Alembic commands ###
